baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "GCC-NUS"
theme = "creative"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Your name"
	description = "Your description"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "GCC-NUS"

		[params.navigation.links]
			about     = "About"
			services  = "Activities"
			portfolio = "Events"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "GCC - NUS"
		subtitle   = "[Lorem](//google.com) Founded in 2015, GCC-NUS is a nonprofit, nonpartisan organization for NUS students of all nationalities looking to engage China’s emergence as a global power."
		buttonText = "Find out more"


	# About section
	# [params.about]
	#	headline    = "The Story of Us"
	#	description = "[Lorem](//Cgoogle.com) GCC connects future leaders from all nations and assists them in developing the skills and friendships necessary to succeed both in China and internationally.Our website is coming soon. If you know us, or have some work for us, feel free to drop an email at info@gccnus.org."
		# buttonText  = "Get started!"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Sign up for the upcoming events!"

		[params.aside.button]
			text = "Sign up now"
			link = "www.facebook.com/pages/gccnus.org"

	# Contact section
	[params.contact]
		headline = "Join us!"
		description = "Ready to join GCC? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "WeChat ID: GCC-NUS"
		# like us on wechat and find out more
		email = "talent@gccnus.org"
		# indicate your area of interest and attach your CV along with the email


	# Service section
	[params.services]
		headline = "Out Partners"

        [[params.services.list]]
			icon = "fa-paper-plane"
			title = "China Business Centre – NUS Business School"
			description = ""

		[[params.services.list]]
            icon = "fa-newspaper-o"
            title = "Business China"
            description = ""



